export const actionTypes = {
// ACCOUNT ACTIONS:
    // LOGIN ACTIONS:
    POST_LOGIN_START: "POST_LOGIN_START",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
    // REGISTER ACTIONS:
    POST_REGISTER_START: "POST_REGISTER_START",
    POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
    POST_REGISTER_FAIL: "POST_REGISTER_FAIL"
}