export const actionTypes = {
// ACCOUNT ACTIONS:
    // LOGIN ACTIONS:
    POST_LOGIN_START: "POST_LOGIN_START",
    POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
    POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
    // REGISTER ACTIONS:
    POST_REGISTER_START: "POST_REGISTER_START",
    POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
    POST_REGISTER_FAIL: "POST_REGISTER_FAIL",
// DASH ACTIONS:
    // Get user's Boards
    GET_BOARDS_START: "GET_BOARDS_START",
    GET_BOARDS_SUCCESS: "GET_BOARDS_SUCCESS",
    GET_BOARDS_FAIL: "GET_BOARDS_FAIL",
// BOARD ACTIONS:
    // Get Complete Board.
    GET_COMPLETE_BOARD_START: "GET_COMPLETE_BOARD_START",
    GET_COMPLETE_BOARD_SUCCESS: "GET_COMPLETE_BOARD_SUCCESS",
    GET_COMPLETE_BOARD_FAIL: "GET_COMPLETE_BOARD_FAIL"
}